# Generated by Django 4.1.6 on 2023-02-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicationmodel",
            old_name="bankstatment",
            new_name="bankStatementFile",
        ),
        migrations.RenameField(
            model_name="applicationmodel",
            old_name="gassbill",
            new_name="gasBillFile",
        ),
        migrations.RenameField(
            model_name="applicationmodel",
            old_name="kebill",
            new_name="kekeBillFilebill",
        ),
        migrations.RenameField(
            model_name="applicationmodel",
            old_name="nicpic",
            new_name="nicPicFile",
        ),
        migrations.RenameField(
            model_name="applicationmodel",
            old_name="profilePic",
            new_name="profilePicFile",
        ),
    ]
